# 1. 빌드 환경
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["INcheonChurchWeb.csproj", "./"]
RUN dotnet restore "INcheonChurchWeb.csproj"
COPY . .
RUN dotnet publish "INcheonChurchWeb.csproj" -c Release -o /app/publish

# 2. 실행 환경
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "INcheonChurchWeb.dll"]