// <auto-generated />
using System;
using Church.Home.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Church.Home.Data.Migrations
{
    [DbContext(typeof(HomeDbContext))]
    partial class HomeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Church.Home.Data.Notice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Greeting")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("Church.Home.Data.NoticeLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoticeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoticeId");

                    b.ToTable("NoticeLinks");
                });

            modelBuilder.Entity("Church.Home.Data.NoticeSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoticeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NoticeId");

                    b.ToTable("NoticeSections");
                });

            modelBuilder.Entity("Church.Home.Data.NoticeWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activity")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoticeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Offering")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prayer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scripture")
                        .HasColumnType("TEXT");

                    b.Property<string>("SermonTitle")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NoticeId");

                    b.ToTable("NoticeWeeks");
                });

            modelBuilder.Entity("Church.Home.Data.ParentAccount", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ParentAccounts");
                });

            modelBuilder.Entity("Church.Home.Data.PortalProfile", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinisterName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinisterPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinisterTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motto")
                        .HasColumnType("TEXT");

                    b.Property<string>("MottoVerse")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenChatCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenChatUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoAlbumUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("YouTubeUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId");

                    b.ToTable("PortalProfiles");
                });

            modelBuilder.Entity("Church.Home.Data.NoticeLink", b =>
                {
                    b.HasOne("Church.Home.Data.Notice", null)
                        .WithMany("Links")
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Church.Home.Data.NoticeSection", b =>
                {
                    b.HasOne("Church.Home.Data.Notice", null)
                        .WithMany("Sections")
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Church.Home.Data.NoticeWeek", b =>
                {
                    b.HasOne("Church.Home.Data.Notice", null)
                        .WithMany("Weeks")
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Church.Home.Data.Notice", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Sections");

                    b.Navigation("Weeks");
                });
#pragma warning restore 612, 618
        }
    }
}
